src/ui/Loader.tsx
just a tailwind property that did not belong there.
=> FIX - Issue #15 - removed white background from bounce loader

src/components/Navigation.tsx
**fix**: I decreased the transition duration from the default motion.div value to **0.15** for Issue #16
=> Added transition duration to VisibleSectionHighlight and ActivePageMarker

src/app/docs/components/text/page.mdx, src/components/PreviewCode/Text.tsx
Since the text ticker component is using an animated counter, there's a slight content shift happening due to numbers being different size. We fix it by adding `tabular-nums`.
You can see more at :
- [https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant-numeric](https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant-numeric)
- [https://twitter.com/jh3yy/status/1715409590320288041](https://twitter.com/jh3yy/status/1715409590320288041)
=> style: use tabular-nums for text ticker wrapper

src/app/docs/components/pricing/page.tsx
Fix mobile responsiveness issue in pricing page code tab
This pull request addresses an issue where the code tab in the pricing page was not rendering correctly on mobile devices.
- Adjusted CSS to prevent code preview content from overflowing the page on smaller screens.
Attached screenshots:
- Before: [Link](https://github.com/Ansub/SyntaxUI/assets/44539538/4113c3b6-362e-4ea1-9eeb-f07c18c1e724)
- After: [Link](https://github.com/Ansub/SyntaxUI/assets/44539538/d48003ce-b5d5-4035-ba24-aedbfb511fb8)
=> fix : pricing page code tab responsive issue

src/components/PreviewCode/LineTabs.tsx
Issue reported by @Ansub
Reason: The 'size-full' class was not being applied.
Fix: Added 'h-full w-full' classes.
=> fix: fixed a bug where the line on the LineTab is not visible

src/components/code/Code.tsx, src/components/code/CodeGroup.tsx, src/components/code/CodeGroupFromFile.tsx, src/components/code/ComponentPreview.tsx, src/components/code/CopyButton.tsx, src/components/code/PreviewCodeGroup.tsx
I added documentation to the code related components in `src/components/code/`.
Fixes #116 
- Added code documentation to 
- `Code.tsx`
- `CodeGroup.tsx`
- `CodeGroupFromFile.tsx`
- `ComponentPreview.tsx`
- `PreviewCodeGroup.tsx`
=> docs: added documentation to code components

src/app/docs/components/input/page.mdx, src/showcase/components/input/TagInput.tsx
Added check for `button` click in `onBlur` handler.
if the user clicks on `button`, we assume that the user wants to do some other task, so we don't update the `keywords` state.
Fixes #115  
- `TagInput.tsx`
https://github.com/Ansub/SyntaxUI/assets/114096753/8aa67a6b-5317-47ff-be1f-84ffe9b27f9a
=> Add check for `button` click in `onBlur` handler

src/components/code/Code.tsx, src/components/code/CopyButton.tsx
Moved the ClipboardIcon component from Code.tsx to CopyButton.tsx
Fixes #126 
- Moved ClipboardIcon from Code.tsx to CopyButton.tsx
=> moved ClipboardIcon from Code.tsx to CopyButton.tsx

src/app/docs/components/input/page.mdx
Related to #124
Removes the unnecessary backslash from the markdown code snippet in `src/app/docs/components/input/page.mdx`.
=> bug: Remove unnecessary backslash in markdown code snippet

src/app/docs/components/input/page.mdx, src/showcase/components/input/TagInput.tsx
When pressing enter do not and empty keyword when the `input value` is empty.
Fixes #125 
- `TagInput.tsx`
- `docs/components/input/page.mdx`
https://github.com/Ansub/SyntaxUI/assets/114096753/a887dbd0-b7bf-4c64-b7ca-64abfbd2c265
=> fix: empty keyword on enter.

src/components/code/Code.tsx, src/components/code/ComponentPreview.tsx, src/components/code/theme.ts, src/styles/tailwind.css
using `react-syntax-highlighter` in Code now / ComponentPreview references Code again / customizable prism theme
Fixes #135 
- Using `react-syntax-highlighter` instead of `codeToHtml` in `src/components/code/Code.tsx`
- Using `Code` instead of `react-syntax-highlighter` in `src/components/code/ComponentPreview.tsx` to only reference `react-syntax-highlighter` in one place
- `react-syntax-highlighter` uses a theme defined in `src/components/code/theme.ts`
- theme is based on css variables in `src/styles/tailwind.css`
- available tokens are defined at https://prismjs.com/tokens.html
=> fix: shiki -> react-syntax-highlighter 

src/components/code/ComponentPreview.tsx
The Tailwind and Framer Motion icon's were aligned to the top instead of the center.
Fixes #150 
- I removed the bare `<div>`s from around the `TooltipeProviders` in `src/components/code/ComponentPreview.tsx`
Before:
After: 
=> fix: Tailwind/Framer Motion Icon Vertical Alignment

credits.md, src/app/docs/components/button/shine-button/page.mdx, src/showcase/components/button/ShineButton.tsx, src/showcase/ui-group/ButtonCards.tsx
This pull request adds a new React component called `ShineButton` to the project. The component renders a button with a shining effect that animates on hover.
Used **bg-[#FF1059]** (this looks good and punching) instead of **bg-red-500** 
- Added a new file `ShineButton.tsx` in the `components/button` folder with the `ShineButton` component.
- Implemented the shining effect animation using Tailwind CSS.
https://github.com/Ansub/SyntaxUI/assets/92677078/1394899a-f29a-4bff-afa6-0630d9d18703
The `ShineButton` component can be used throughout the application to add a visually appealing and interactive button element. It is built using React and styled with Tailwind CSS. The shining effect is achieved by creating a skewed overlay div that animates from left …
=> feat: Add New Shine Button 

src/app/docs/components/button/gradient-fill-button/page.mdx, src/showcase/components/button/GradientFillButton.tsx
I re-implemented the `GradientFillButton` using only Tailwind
Fixes #157 
- changed `src/showcase/components/button/GradientFillButton.tsx` to only use tailwind
https://github.com/Ansub/SyntaxUI/assets/16091805/50a984a8-974b-410e-9562-36ab86387218
=> fix: GradientFillButton using only Tailwind

src/components/Layout.tsx
This PR addresses a bug where the footer incorrectly appeared at the top instead of the bottom on components not filling the entire viewport. By adding `min and max height` the footer now consistently stays at the bottom as intended, improving overall usability.
Fixes #159 
- Added `min` and `max height` to fix this issue
=> Fix: footer positioning issue

src/components/Header.tsx, src/components/MobileNavigation.tsx
Fixed Navbar mobile responsive issue
Fixes #162 
- Remove SyntaxUI text in mobile view to fix the responsive issue
- Expand ToggleIcon width for enhanced usability and clickability
=>  🐞 Fix Navbar responsive issue

src/app/(docs)/components/button/border-glow-button/page.mdx, src/showcase/components/button/BorderGlowButton.tsx
fixed `BorderGlowButton` using only Tailwind .
Fixes #176 
- changed `src/showcase/components/button/BorderGlowButton.tsx` to only use tailwind
- Change : remove note  This component requires Framer Motion from `src/app/(docs)/components/button/border-glow-button/page.mdx`
=> fix: BorderGlowButton only Tailwind

next.config.mjs
change images : {domain :["//"]} to images: remotePatterns
[Refer](https://nextjs.org/docs/messages/next-image-unconfigured-host) 
Because `images:domain `is deprecated
Fixes #181 
- Change file ` next.config.mjs`
=> Fixed :  images : {domain :[..]} to images: remotePatterns

src/showcase/components/toggle/IconToggle.tsx, src/showcase/components/toggle/SimpleToggle.tsx
The Framer Motion Layout has been implemented correctly, based on my knowledge.
The current usage:
- The parent component is a non-motion component with a non-animatable style property (in this case, Justify-content) that switches between 'end' and 'start'.
- The child component is a motion component with a layout set to true.
**Please note that animating x from 0 to 100% is more performant and reliable than manipulating the DOM. However, I updated the code based on @Ansub 's suggestion.**
File modified:
> src/showcase/components/toggle/IconToggle.tsx
> src/showcase/components/toggle/SimpleToggle.tsx
=> Updated Icon/Simple toggles

src/showcase/components/logo-cloud/AnimatedLogoCloud.tsx
- added fade effect on sides of LogoCloud
- changed width to 100% so the effect works on multiple sizes
Fixes #192 
- I used a `linear-gradient` to mask out the `AnimatedLogoCloud` on the left and right sides to add a fade effect.
- I added `w-full` to the containers to make the sizing work so that the `linear-gradient` applies to the full width instead of applying to hidden sections (caused by `overflow-hidden`) 
https://github.com/Ansub/SyntaxUI/assets/16091805/59c4183f-9d9a-421d-a698-1742119228cf
I chose to use `maskImage` instead of using `span`s with a basic gradient so that it will work on any background color.
=> fix: added fade to logo cloud

src/app/(docs)/components/toggle/simple-toggle/page.mdx, src/showcase/components/toggle/SimpleToggle.tsx
I removed the Framer Motion dependency from the Simple Toggle Component
Fixes #200 
- modified `src/showcase/components/toggle/SimpleToggle.tsx`
- removed framer motion references
- added local version of the `cn` function to the file so that it is visible in the code preview
- changed from arbitrary pixel sizes to using build in tailwind sizes (width, height, and padding)
- implemented same transition using raw tailwind instead of tailwind + framer motion
- modified `src/app/(docs)/components/toggle/simple-toggle/page.mdx`
- removed `usingFramer` tag from docs page
=> fix: Removed Framer Motion from Simple Toggle

credits.md, src/app/(docs)/components/toggle/icon-toggle/page.mdx, src/showcase/components/toggle/IconToggle.tsx
Removed the Framer Motion dependency from the Icon Toggle Component .
Fixes #201 
- Modified `src/showcase/components/toggle/IconToggle.tsx`
- Removed framer-motion references.
- Achieved the same transition effect using Tailwind CSS directly, instead of combining it with Framer Motion.
- Added a local version of the `cn` function for code preview visibility.
- Modified `src/app/(docs)/components/toggle/icon-toggle/page.mdx`
- Removed `usingFramer` prop from Component Preview.
- Added `usingCn` prop in Component Preview.
=> [Feature]: Removed Framer-Motion from Icon Toggle

tailwind.config.ts
I added #fafafa to gray.100 in tailwind.config.ts
This change relates to issue [#230](https://github.com/SyntaxUI/syntaxui/issues/230)
Fixes # (230)
Adding an option to use gray.100 in application.
N/A
=> Add #fafafa to gray.100 in tailwind.config.ts for issue 230

package-lock.json, src/components/Footer.tsx
I added the hex code `#fafafa` to show on the social icons in dark mode for the Footer
https://github.com/SyntaxUI/syntaxui/issues/229
Fixes # (229)
- Change 1
- Change 2
- ...
N/A
=> Better color for Social Icons in Footer #229

src/app/templates/[id]/page.tsx
Incorrect pricing displayed for the Stoic template. The template listing was static.
Updated the template listing to be dynamic, pulling pricing data directly from the `template` object. This ensures that the displayed prices are always current.
- Changed static pricing display to dynamic fields sourced from `template.price` and `template.originalPrice`.
=> Fix issue 239: Incorrect pricing displayed for the stoic template

src/components/code/Code.tsx
changes the border color that causing the issue in in dark mode in ComponentPreview component from navigating from code to preview.It was coded border-gray-600 in dark mode and for light mode in code component that causing inconsistency in color.
https://github.com/SyntaxUI/syntaxui/issues/243
Fixes # (issue)
- Change -> change the border color from bg-gray-600 to bg-gray-700 
[Screencast from 2024-06-25 21-25-10.webm](https://github.com/SyntaxUI/syntaxui/assets/120778312/f7ecdd5b-195c-4536-b3db-6e3b3b9983a9)
- [✅ ] I have rebased my branch on top of the latest `main` branch.
- [ ✅] I have tested the changes locally
- [✅ ] I ran `npm run build` and build is successful
=> fix the border color changing issue when navigating from code to preview in dark mode.

src/app/(docs)/components/input/page.mdx, src/showcase/components/input/TagInput.tsx
This pull request addresses the issue of duplicate tags being added in the TagInput component. A unique prop has been introduced to control whether duplicate tags should be allowed.
Fix #247 
1. **Component Enhancement**:
- Added a new prop `unique` to the `TagInput` component.
- Updated the keyword handling logic to prevent duplicates when `unique` is set to `true`.
2. **Keyword Addition**:
- When the `Enter` key or comma is pressed, the component adds the new keyword if it's not already present in the list.
- Paste handling ensures that only unique keywords are added to the list when `unique` is set to `true`.
- **Unique Keywords**: When the `unique` prop is enabled, duplicate keywords are prevented.
```jsx
<TagInput unique />
```
Before:
After:
=> Feat:  Duplicate Tags in TagInput Component

src/components/code/ComponentPreview.tsx
added appropriate overflow-hidden
Fixes #250 
- Added `overflow-hidden` to nearest ancestor element that contains `relative` since the `Banner` uses `absolute`.
=> fix: Banner Not Hiding Properly
