- src/app/docs/animations/heartbeat-button/page.mdx
Your prettier doesn't format like your codebase. I had to format it manually.
But the heartbeat page had the skew animation and not the heartbeat animation. I took this from the source of the button and added it to the code to copy.
> fix: heartbeat page was using skew keyframes

- src/app/docs/animations/skewed-infinite-scroll/page.mdx
Same as #23 but the other way around. :D
> fix: skew scroll page was using heartbeat keyframes

- package-lock.json
- package.json
- src/app/docs/components/tabs/page.mdx
- src/app/docs/page.mdx
- src/components/PreviewCode/IconTabs.tsx
- src/components/PreviewCode/LineTabs.tsx
- src/ui/Tabs.tsx
1. Added a new tabs variants: 
- Line tabs
- Icon Tabs
2. (Updated the Docs) Added the new Tabs variants to the docs
On branch Added-a-new-tabs-variants-+-updated-the-website-docs-
Changes to be committed:
modified:   package-lock.json
modified:   package.json
modified:   src/app/docs/components/tabs/page.mdx
new file:   src/components/PreviewCode/IconTabs.tsx
new file:   src/components/PreviewCode/LineTabs.tsx
modified:   src/ui/Tabs.tsx
Preview 
https://github.com/Ansub/SyntaxUI/assets/97196113/057e0024-3f8d-4c41-b660-5f0ac7ded758
https://github.com/Ansub/SyntaxUI/assets/97196113/8c732c51-ee97-4604-9e6f-f4db554515e3
> feat: Added a new tabs variants

- src/app/docs/components/button/3d-button/page.mdx
- src/components/Cards/ButtonCards.tsx
- src/components/ComponentCards.tsx
- src/ui/button.tsx
+ Style: Fixed an overflow issue with the 3D button that can be seen on dark mode pages.
+ Refactor: Fixed an underline shown on the buttons on the documentation page.
> Style & Refactor: Fixed Overflow and Underline Issue

- README.md
- src/app/docs/hooks/useMediaSizes/page.mdx
- src/app/docs/page.mdx
- src/components/HooksCards.tsx
- src/components/Navigation.tsx
feat: #38 
Added `useMediaSizes` to docs with a simple example.
> feat: Added useMediaSizes to docs

- src/components/ComponentCards.tsx
> Fixed ComponentCards id numbering issue

- package-lock.json
- package.json
Successfully able to format text in mdx file, locally !
[Screencast from 24-04-24 10:34:43 PM IST.webm](https://github.com/Ansub/SyntaxUI/assets/115932772/80bde715-6107-4353-9d9f-2afd5ff060e5)
> chore: devDependencies updated

- package-lock.json
- package.json
> Revert "chore: devDependencies updated"

- .github/ISSUE_TEMPLATE/chore_task.md
> Added a Chore task issue template

- src/app/docs/components/button/heartbeat-button/page.mdx
- src/showcase/components/button/HeartbeatButton.tsx
fix: #79 
- Updated HeartbeatButton's label to say `Syntax UI`
- Updated padding in HeartbeatButton to match other buttons
- Updated `src/app/docs/components/button/heartbeat-button/page.mdx` to match new button code
> updated the HeartbeatButton to say 'Syntax UI' and updated the padding to match the other buttons / updated the docs to reflect change

- src/components/cards/ButtonCards.tsx
fix: #84 
modified `src/components/cards/ButtonCards.tsx`
- updated link in 3D Button's card from `3d-button` to `three-d-button`
> Updated link from '3d-button' to 'three-d-button'

- src/app/page.tsx
- src/styles/tailwind.css
- tailwind.config.ts
feat: #73 
- Moved the DiscordButton to its own component (still in the same file: `src/app/page.tsx`)
- Added options for showing the borderAnimation and showing the backgroundAnimation that both default to false
- Added custom css properties (`--discord-button-angle` and `--discord-button-x`) to `src/styles/tailwind.css` 
- Added keyframes and animation to animate the custom css properties to `tailwind.config.ts`
> added cool border effect for the DiscordButton

- src/app/docs/components/toggle/neobrutalism-toggle/page.mdx
- src/components/cards/ToggleCards.tsx
- src/showcase/components/toggle/NeobrutalismToggle.tsx
feat: #93 
Added a Neobrutalism Toggle to showcase and to docs
> Neobrutalism Toggle

- CONTRIBUTING.md
fix: #103 
Added information on 
- where to place new features
- where to place new docs
- how to write new docs
- how to use `<ComponentPreview`
- how to add to UI Groups properly
- how to add to the Navigation links properly
- how to get help for further questions (issues and discord)
> fix: updating CONTIBUTING.md

- src/app/docs/layout.tsx
> Revert "fix: duplicate html and body tags"

- .vscode/settings.json
> feat: added customLabels support for pages, layouts, docs, showcases, and components

- src/showcase/components/features/SpringAnimatedFeatures.tsx
Please provide a brief description of the changes made in this pull request.
Please link to the issue that this pull request addresses or resolves.
Fixes # (issue)
- there were same ID under ProjectsData Array for SyntaxUI and PrettyFolio
- [ ✅] I have tested the changes locally
- [✅ ] I ran `npm run build` and build is successful
- [ ✅] I have added necessary documentation (if applicable)
- [ ✅] I have updated the credits.md file (if applicable)
> Updated ID for Sring Animated Feature Component

- credits.md
- src/app/docs/components/button/border-rotate-button/page.mdx
- src/app/sitemap.xml
- src/showcase/components/button/BorderRotateButton.tsx
- src/showcase/ui-group/ButtonCards.tsx
I added a Border Rotate Button
Fixes: #137 
- Added `BorderRotateButton` to `src/showcase/components/button/BorderRotateButton.tsx`
- Added docs to `src/app/docs/components/button/border-rotate-button/page.mdx`
- uses `ComponentPreview`
- Added card to UI Group `src/showcase/ui-group/ButtonCards.tsx`
- Added to `credits.md`
https://github.com/Ansub/SyntaxUI/assets/16091805/d54f491d-4e8d-401d-ba4d-6cb1d723410b
> feat: Border Rotate Button

- src/components/Logos/Framer.tsx
- src/components/Logos/Tailwind.tsx
- src/showcase/ui-group/ButtonCards.tsx
> Show Tailwind & Framer Motion logo in Button Cards

- src/showcase/components/toggle/SimpleToggle.tsx
used Framer [Layout](https://www.framer.com/motion/layout-animations/) feature to simplify the code for this animation, same can be done for other toggles aswell.
cc: @epoll31 @ITs-AIKO 
https://github.com/Ansub/SyntaxUI/assets/12985873/07064181-8764-4d58-aee1-1cef060370b2
> feat: used framer-motion layout to simplify toggle component

- src/components/code/ComponentPreview.tsx
- src/components/reusable/AnimatedTabs.tsx
Please provide a brief description of the changes made in this pull request.
Please link to the issue that this pull request addresses or resolves.
https://github.com/Ansub/SyntaxUI/issues/163
Fixes # (#163)
- [ Yes] I have tested the changes locally
- [Yes ] I ran `npm run build` and build is successful
> fix : fix the css problem in component preview

- .github/workflows/greetings.yml
This PR resolves the issue mentioned in #89  , kindly review the PR, and merge it whenever you get chance.
> feat: added greeting workflow 🤖

- credits.md
Added my credits in credits.md, kindly review and merge it.
> docs: added credits

- src/components/Navigation.tsx
- src/components/Tag.tsx
> ✨ added new badge in navigation

- src/app/providers.tsx
Added light theme as default
- added `defaultTheme="light"` to `src/app/providers.tsx`
> set default theme to light

- credits.md
- src/app/(docs)/effects/background/grid/page.mdx
- src/showcase/effects/BackgroundGrid.tsx
- src/showcase/ui-group/BackgroundCards.tsx
I fixed BackgroundGrid to be more similar to the other backgrounds. I also removed the `usingCn` flag.
- updated BackgroundGrid card in the ui-group to me more similar to the other background cards
- updated `BackgroundGrid` in showcase to be more similar to the other backgrounds
- removed `preview` override and `usingCn` in BackgroundGrid docs page
- updated the link in `credits.md` to reflect the new url
> Fix: background grid display issue

- src/components/code/Code.tsx
Fix mobile responsiveness issue in code component
This pull request addresses an issue where the code is overflowing on mobile devices.
Changes
Adjusted tailwind utility classes to prevent code preview content from overflowing the page on smaller screens.
Attached screenshots:
Before: [Link](https://github.com/SyntaxUI/syntaxui/assets/44539538/a9f68cd6-2ed1-4d48-b1a0-57b0214da364)
> fix : responsive issue in code component

- src/app/templates/[id]/page.tsx
Added a tailwind class to fix responsive issues on stoic template page
Fixes #241 
- Added Tailwind breakpoint class lg: to fix the overlapping issue
- [✅ ] I have rebased my branch on top of the latest `main` branch.
- [✅ ] I have tested the changes locally
- [✅ ] I ran `npm run build` and build is successful
> Added a tailwind class to fix responsive issue on stoic template page

- src/components/code/Code.tsx
added prose classname 
Fixes #253 
- Added class `prose` to code component
Before : ![Screenshot 2024-07-06 160203](https://github.com/SyntaxUI/syntaxui/assets/44539538/baf22795-1d02-4a6d-8819-fa0712a209fc)
After :  ![Screenshot 2024-07-06 160223](https://github.com/SyntaxUI/syntaxui/assets/44539538/cba6e85e-20d9-4e8f-a78f-c140aaf3b37e)
> fix : code highlighter is not working properly

- src/app/(docs)/components/button/magnetic-button/page.mdx
- src/showcase/components/button/MagneticButton.tsx
- src/showcase/ui-group/ButtonCards.tsx
Added a magnetic button component
https://github.com/SyntaxUI/syntaxui/assets/73949924/2fce72c6-8390-4f1b-b61e-e289697d1deb
> added magnetic-button

- .github/pull_request_template.md
Added a dark theme support check to pr template
Fixes #260 
- Added a dark theme support check to pr template
> feat: dark theme check in pr template
